version: "3.8"
services:
  web:
    build: php7.4-apache
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "81:8080"
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root123
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser123
volumes:
  db_data: {}

